[versions]
agp = "8.13.0"
kotlin = "2.1.0"
composeBom = "2024.12.01"
coreKtx = "1.15.0"
lifecycle = "2.9.0"
activityCompose = "1.10.0"
materialIcons = "1.7.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIcons" }

core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

junit = { module = "junit:junit", version = "4.13.2" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.2.1" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.6.1" }
